make sftp-server portable
webosbrew/webos-homebrew-channel pull request #153
Opened 2023-09-21 07:57 UTC by mariotaku

2023-09-22 01:02 UTC, kitsuned requested changes

2023-09-22 01:02 UTC, kitsuned commented on tools/patches/dropbear-localoptions.h
> +        last_slash = strrchr(path, '/');
i guess you meant `dropbear_path`

2023-09-22 01:14 UTC, kitsuned approved these changes

2023-10-06 12:41 UTC, throwaway96 commented on tools/patches/dropbear-localoptions.h
> +        last_slash = strrchr(dropbear_path, '/');
Why not use `dirname()`?

2023-12-06 04:55 UTC, mariotaku commented
superseded by #155

2023-12-06 04:55 UTC, closed without merging